#!/usr/bin/env bun
import { join } from "node:path"

export const SUPPORT_START = "<!-- render:support-table:start -->"
export const SUPPORT_END = "<!-- render:support-table:end -->"

export type ChecklistItem = {
  readonly id: string
  readonly step: string
  readonly pass: string
  readonly not_applicable_for: ReadonlyArray<string>
  readonly notes?: string
}

export type Checklist = {
  readonly items: ReadonlyArray<ChecklistItem>
}

function repoRoot(): string {
  return join(import.meta.dir, "..")
}

function yamlQuote(value: string): string {
  return JSON.stringify(value)
}

export function parseChecklist(text: string): Checklist {
  const parsed = Bun.YAML.parse(text) as { items?: unknown }
  if (!parsed || !Array.isArray(parsed.items)) {
    throw new Error("device-checklist.yaml needs an items list.")
  }
  const items: ChecklistItem[] = []
  for (const raw of parsed.items) {
    if (!raw || typeof raw !== "object") {
      throw new Error("Each checklist item must be a map.")
    }
    const item = raw as {
      id?: unknown
      step?: unknown
      pass?: unknown
      not_applicable_for?: unknown
      notes?: unknown
    }
    if (typeof item.id !== "string" || typeof item.step !== "string" || typeof item.pass !== "string") {
      throw new Error("Each checklist item needs id, step, and pass.")
    }
    const families = item.not_applicable_for
    if (!Array.isArray(families) || families.some((family) => typeof family !== "string")) {
      throw new Error(`${item.id} needs not_applicable_for as a list of strings.`)
    }
    const notes = item.notes
    items.push({
      id: item.id,
      step: item.step,
      pass: item.pass,
      not_applicable_for: families,
      ...(typeof notes === "string" ? { notes } : {}),
    })
  }
  if (items.length === 0) {
    throw new Error("device-checklist.yaml has no items.")
  }
  return { items }
}

export function extractSupportTable(source: string): string {
  const lines = source.split("\n").filter((line) => line.startsWith("|"))
  if (lines.length < 2) {
    throw new Error("docs/support-table.md has no markdown table.")
  }
  return `${lines.join("\n")}\n`
}

export function applySupportTable(readme: string, table: string): string {
  const start = readme.indexOf(SUPPORT_START)
  const end = readme.indexOf(SUPPORT_END)
  if (start === -1 || end === -1 || end <= start) {
    throw new Error("README.md needs support table render markers.")
  }
  const before = readme.slice(0, start + SUPPORT_START.length)
  const after = readme.slice(end)
  return `${before}\n${table.trimEnd()}\n${after}`
}

function fieldId(item: ChecklistItem): string {
  return item.id.toLowerCase().replaceAll("-", "_")
}

function withStop(text: string): string {
  const trimmed = text.trim()
  if (/[.!?]$/.test(trimmed)) {
    return trimmed
  }
  return `${trimmed}.`
}

function itemDescription(item: ChecklistItem): string {
  const parts = [`Pass: ${withStop(item.pass)}`]
  if (item.not_applicable_for.length > 0) {
    parts.push(`Not applicable for ${item.not_applicable_for.join(", ")}.`)
  }
  if (item.notes) {
    parts.push(withStop(item.notes))
  }
  return parts.join(" ")
}

export function renderDeviceVerificationForm(checklist: Checklist): string {
  const lines: string[] = [
    "# Generated by scripts/render.ts from docs/verification/device-checklist.yaml.",
    "# Do not edit this file.",
    "name: Device verification",
    "description: Report a Device Checklist run on real hardware.",
    "title: \"[verification] \"",
    "body:",
    "  - type: markdown",
    "    attributes:",
    "      value: |",
    "        Run the Device Checklist on stock firmware after a Sync of the Verification Library.",
    "        Attach SysInfo and SysInfoExtended from iPod_Control/Device on the Device.",
    "        Use the GitHub attach control below the form.",
  ]

  const inputs: ReadonlyArray<{ id: string; label: string; description: string }> = [
    {
      id: "model_num_str",
      label: "ModelNumStr",
      description: "Copy ModelNumStr from SysInfo on the Device.",
    },
    {
      id: "apple_model_number",
      label: "Apple model number",
      description: "Apple model number from the Device or its retail box.",
    },
    {
      id: "firmware",
      label: "Firmware",
      description: "Firmware version from Settings, About.",
    },
    {
      id: "filesystem",
      label: "Filesystem",
      description: "Volume format of the Device, such as FAT32.",
    },
    {
      id: "host_os",
      label: "Host OS",
      description: "Host operating system and version that ran omatune.",
    },
    {
      id: "omatune_version",
      label: "omatune version",
      description: "omatune version or GitHub Release tag.",
    },
  ]

  for (const input of inputs) {
    lines.push(`  - type: input`)
    lines.push(`    id: ${input.id}`)
    lines.push("    attributes:")
    lines.push(`      label: ${yamlQuote(input.label)}`)
    lines.push(`      description: ${yamlQuote(input.description)}`)
    lines.push("    validations:")
    lines.push("      required: true")
  }

  for (const item of checklist.items) {
    lines.push("  - type: dropdown")
    lines.push(`    id: ${fieldId(item)}`)
    lines.push("    attributes:")
    lines.push(`      label: ${yamlQuote(`${item.id}: ${item.step}`)}`)
    lines.push(`      description: ${yamlQuote(itemDescription(item))}`)
    lines.push("      options:")
    lines.push("        - pass")
    lines.push("        - fail")
    lines.push("        - not applicable")
    lines.push("    validations:")
    lines.push("      required: true")
  }

  lines.push("  - type: textarea")
  lines.push("    id: devices_json")
  lines.push("    attributes:")
  lines.push('      label: "devices --json"')
  lines.push('      description: "Paste the full output of omatune devices --json."')
  lines.push("      render: shell")
  lines.push("    validations:")
  lines.push("      required: true")
  lines.push("  - type: markdown")
  lines.push("    attributes:")
  lines.push("      value: |")
  lines.push("        Attach SysInfo files from the Device.")
  lines.push("        Copy SysInfo and SysInfoExtended from iPod_Control/Device on the mounted volume.")
  lines.push("        Use the attach control below this form.")
  lines.push("")
  return lines.join("\n")
}

export type GeneratedFiles = {
  readonly readme: string
  readonly form: string
}

export function renderGenerated(input: {
  readonly readme: string
  readonly supportTableSource: string
  readonly checklistSource: string
}): GeneratedFiles {
  const table = extractSupportTable(input.supportTableSource)
  const checklist = parseChecklist(input.checklistSource)
  return {
    readme: applySupportTable(input.readme, table),
    form: renderDeviceVerificationForm(checklist),
  }
}

export function staleGenerated(actual: GeneratedFiles, expected: GeneratedFiles): string[] {
  const stale: string[] = []
  if (actual.readme !== expected.readme) {
    stale.push("README.md")
  }
  if (actual.form !== expected.form) {
    stale.push(".github/ISSUE_TEMPLATE/device-verification.yml")
  }
  return stale
}

async function loadSources(): Promise<{
  readmePath: string
  formPath: string
  readme: string
  supportTableSource: string
  checklistSource: string
  form: string
}> {
  const root = repoRoot()
  const readmePath = join(root, "README.md")
  const formPath = join(root, ".github/ISSUE_TEMPLATE/device-verification.yml")
  const readmeFile = Bun.file(readmePath)
  const formFile = Bun.file(formPath)
  return {
    readmePath,
    formPath,
    readme: await readmeFile.text(),
    supportTableSource: await Bun.file(join(root, "docs/support-table.md")).text(),
    checklistSource: await Bun.file(join(root, "docs/verification/device-checklist.yaml")).text(),
    form: formFile.size > 0 ? await formFile.text() : "",
  }
}

async function writeGenerated(): Promise<void> {
  const sources = await loadSources()
  const generated = renderGenerated(sources)
  await Bun.write(sources.readmePath, generated.readme)
  await Bun.write(sources.formPath, generated.form)
}

async function checkGenerated(): Promise<void> {
  const sources = await loadSources()
  const generated = renderGenerated(sources)
  const stale = staleGenerated({ readme: sources.readme, form: sources.form }, generated)
  if (stale.length > 0) {
    throw new Error(`Generated files are stale: ${stale.join(", ")}. Run bun scripts/render.ts.`)
  }
}

async function main(): Promise<void> {
  const mode = Bun.argv[2]
  if (mode === "--check") {
    await checkGenerated()
    return
  }
  if (mode !== undefined) {
    throw new Error("Unknown argument. Use --check or pass no arguments.")
  }
  await writeGenerated()
}

if (import.meta.main) {
  await main()
}
